import type { Metadata } from 'next'
import { Titillium_Web } from 'next/font/google'
import '@/styles/globals.css'
import { cn } from '@/lib/utils'

const genos = Titillium_Web({ subsets: ['latin',"latin-ext"]  , variable: "--font-genos" , weight: "400"  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-genos antialiased",
          genos.variable
        )}>{children}</body>
    </html>
  )
}
